# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('shrinkedURL', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('targetURL', models.CharField(max_length=2083)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
